_target_: ???
loss:
  _target_: src.model.loss.BinaryCrossEntropy

n_documents: ???

metrics:
  - _target_: src.evaluation.Perplexity
    name: ppl
    ranks: [0, 1, 5, 10]
  - _target_: src.evaluation.NDCG
    name: nDCG
    ranks: [0, 1, 5, 10]
  - _target_: src.evaluation.AgreementRatio
    name: agreement_ratio
    disjoint_pairs: False
  - _target_: src.evaluation.PointwiseClassifierCITest
    name: pointwise_ci
    classifier:
      _target_: lightgbm.LGBMClassifier
