_target_: ???
loss:
  _target_: src.model.loss.BinaryCrossEntropy

n_documents: ???

metrics:
  - _target_: src.evaluation.Perplexity
    name: ppl
    ranks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - _target_: src.evaluation.NDCG
    name: nDCG
    ranks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - _target_: src.evaluation.AgreementRatio
    name: agreement_ratio
    disjoint_pairs: False
  - _target_: src.evaluation.PointwiseClassifierCITest
    name: pointwise_ci
    classifier:
      _target_: lightgbm.LGBMClassifier
  - _target_: src.evaluation.ConditionalMutualInformation
    name: cmi
    n_bootstrap: 3
    kl_divergence:
      _target_: src.evaluation.ClassifierKLDivergence
      n_bootstrap: 5
      eta: 0.01
      classifier:
        _target_: lightgbm.LGBMClassifier
