defaults:
  - base

_target_: src.model.RankedDCTR
n_results: "${train_simulator.rank_size}"
optimizer: adam
learning_rate: 0.01

# Click prediction with Beta(alpha=1, beta=1) prior for smoothing
prior_clicks: 1
prior_impressions: 2
