name: cm-bias-evaluation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - torchvision=0.14.0
  - cudatoolkit=11.3
  - hydra-core=1.2.0
  - pandas=1.4.3
  - pyarrow=9.0.0
  - numpy=1.23.2
  - pip=21.2.4
  - rich=12.5.1
  - lightgbm=3.3.3
  - pip:
      - hydra_submitit_launcher==1.2.0
      - lightning==1.8.3
      - pre-commit==2.20.0
      - wget==3.2
      - wandb==0.13.2
